# Fly.io configuration for Code Quality Intelligence Agent
app = "code-quality-agent"
primary_region = "iad"

[build]

[env]
  PORT = "8501"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
