from setuptools import setup, find_packages

setup(
    name="cq-agent",
    version="0.0.1",
    description="Code Quality Intelligence Agent (MVP)",
    author="Sujit Nirmal",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.11",
    install_requires=[
        "typer>=0.9.0",
        "gitpython>=3.1.0",
        "streamlit>=1.28.0",
        "pandas>=2.0.0",
        "plotly>=5.15.0",
        "numpy>=1.24.0",
        "scikit-learn>=1.3.0",
        "python-dotenv>=1.0.0",
        "networkx>=3.0",
        "ruff>=0.1.0",
        "bandit>=1.7.0",
        "pylint>=2.17.0",
        "mypy>=1.0.0",
        "black>=23.0.0",
        "isort>=5.12.0",
        "flake8>=6.0.0",
        "pytest>=7.0.0",
        "pytest-cov>=4.0.0",
        "coverage>=7.0.0",
        "safety>=2.0.0",
        "semgrep>=1.0.0",
        "sourcery>=1.0.0",
        "vulture>=2.0.0",
        "radon>=6.0.0",
        "xenon>=0.8.0",
        "wily>=2.0.0",
        "pycodestyle>=2.10.0",
        "pyflakes>=3.0.0",
        "mccabe>=0.7.0",
        "pyroma>=3.0.0",
        "check-manifest>=0.48.0",
        "pre-commit>=3.0.0",
        "tox>=4.0.0",
        "pip-tools>=7.0.0",
        "pipdeptree>=2.0.0",
        "pip-audit>=2.0.0",
        "pip-check>=2.0.0",
        "pip-review>=1.0.0",
        "pip-upgrade>=1.0.0",
        "pip-autoremove>=0.10.0",
        "pip-tools>=7.0.0",
        "pipdeptree>=2.0.0",
        "pip-audit>=2.0.0",
        "pip-check>=2.0.0",
        "pip-review>=1.0.0",
        "pip-upgrade>=1.0.0",
        "pip-autoremove>=0.10.0",
        "faiss-cpu>=1.7.0",
        "sentence-transformers>=2.2.0",
        "langchain>=0.1.0",
        "langchain-community>=0.0.1",
        "gpt4all>=2.0.0",
    ],
    extras_require={
        "llama-cpp": ["llama-cpp-python>=0.2.0"],
        "gpt4all": ["gpt4all>=2.0.0"],
    },
    entry_points={
        "console_scripts": [
            "cq-agent=cq_agent.cli.main:main",
        ],
    },
)
